// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWPYgU8a4-tEFp9BnaCfRPYHL8P_9Spus',
    appId: '1:142817827453:android:240f9de1bba906f2b2af14',
    messagingSenderId: '142817827453',
    projectId: 'vamos-app-a5f24',
    storageBucket: 'vamos-app-a5f24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdCXCkvudLr8qyNgJdKFHOzFXOjI5zj50',
    appId: '1:142817827453:ios:b075167d2138cb82b2af14',
    messagingSenderId: '142817827453',
    projectId: 'vamos-app-a5f24',
    storageBucket: 'vamos-app-a5f24.firebasestorage.app',
    iosClientId: '142817827453-3i3l6vqokdqi1682q9i1iigek2ppvcu2.apps.googleusercontent.com',
    iosBundleId: 'com.jabsolutions.vamos',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6mhVJREzmdmGzLMqAiAd4OT8wy4S857U',
    appId: '1:142817827453:web:1044cf3b628ecf98b2af14',
    messagingSenderId: '142817827453',
    projectId: 'vamos-app-a5f24',
    authDomain: 'vamos-app-a5f24.firebaseapp.com',
    storageBucket: 'vamos-app-a5f24.firebasestorage.app',
    measurementId: 'G-MMVS86NFQB',
  );

}