import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:vamos/data/models/trip.dart';
import 'package:vamos/data/repositories/firestore_trip_repository.dart';
import 'package:vamos/features/auth/application/auth_notifier.dart';
import 'package:vamos/features/trips/application/my_trips_notifier.dart';

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

/// Holds the result of a successful trip creation so the screen can navigate.
///
/// [tripId] is non-null only after a successful [CreateTripNotifier.create]
/// call. The notifier state is `AsyncData<CreateTripResult>` even before
/// creation — [tripId] is null in the idle state.
class CreateTripResult {
  const CreateTripResult({this.tripId});

  /// The Firestore ID of the newly created trip, or null if no trip has been
  /// created yet in this notifier's lifecycle.
  final String? tripId;
}

// ---------------------------------------------------------------------------
// Notifier
// ---------------------------------------------------------------------------

/// Handles the "Crear viaje" form submission (F1.2).
///
/// Validates inputs, calls [TripRepository.create], and exposes the new
/// [tripId] so the screen can navigate to `/trips/$tripId`.
///
/// autoDispose: the screen owns the lifecycle — the notifier is released when
/// the user navigates away from CreateTripScreen.
class CreateTripNotifier extends AutoDisposeAsyncNotifier<CreateTripResult> {
  @override
  Future<CreateTripResult> build() async {
    return const CreateTripResult();
  }

  /// Validates inputs and creates the trip in Firestore.
  ///
  /// Validation rules (all throw [ArgumentError] if violated):
  ///   - [name] must not be empty or blank
  ///   - [destination] must not be empty or blank
  ///   - [startDate] must be on or before [endDate]
  ///   - [mainCurrency] must not be empty
  ///
  /// On success, [state] becomes `AsyncData(CreateTripResult(tripId: newId))`.
  /// On failure, [state] becomes `AsyncError(...)`.
  Future<void> create({
    required String name,
    required String destination,
    required DateTime startDate,
    required DateTime endDate,
    required String mainCurrency,
    String? coverPhotoURL,
  }) async {
    // Client-side validation
    if (name.trim().isEmpty) {
      state = AsyncError(
        ArgumentError('El nombre del viaje no puede estar vacío.'),
        StackTrace.current,
      );
      return;
    }
    if (destination.trim().isEmpty) {
      state = AsyncError(
        ArgumentError('El destino no puede estar vacío.'),
        StackTrace.current,
      );
      return;
    }
    if (startDate.isAfter(endDate)) {
      state = AsyncError(
        ArgumentError('La fecha de inicio debe ser anterior o igual a la fecha de fin.'),
        StackTrace.current,
      );
      return;
    }
    if (mainCurrency.trim().isEmpty) {
      state = AsyncError(
        ArgumentError('Tenés que elegir una moneda.'),
        StackTrace.current,
      );
      return;
    }

    state = const AsyncLoading();

    state = await AsyncValue.guard(() async {
      final userId = ref.read(currentUserIdProvider);
      if (userId.isEmpty) {
        throw StateError('No hay un usuario autenticado.');
      }

      // Use Firebase Auth displayName as the facilitator alias.
      // Falls back to the user ID if the name is not set (e.g., anonymous).
      final displayName =
          ref.read(authStateProvider).value?.displayName ?? userId;

      final now = DateTime.now();

      final trip = Trip(
        id: '', // ID is generated by Firestore; unused until returned
        name: name.trim(),
        destination: destination.trim(),
        startDate: startDate,
        endDate: endDate,
        mainCurrency: mainCurrency,
        coverPhotoURL: coverPhotoURL,
        facilitatorId: userId,
        memberIds: [userId], // facilitator must be in memberIds from the start
        memberAliases: {userId: displayName}, // X-11: seed alias for the UI
        status: 'active',
        createdAt: now,
        createdBy: userId,
      );

      final tripId = await ref
          .read(tripRepositoryProvider)
          .create(trip, displayName);

      return CreateTripResult(tripId: tripId);
    });
  }
}

/// Riverpod provider for [CreateTripNotifier].
final createTripProvider =
    AsyncNotifierProvider.autoDispose<CreateTripNotifier, CreateTripResult>(
  CreateTripNotifier.new,
);
